hapi:
  port: 5337
  host: '::'
router:
  externalHost: 'localhost.mkg20001.io:5337'
  bindAddress: '::'
tls:
  cert: './path-to-your.cert'
  key: './path-to-your.key'
tokenHash: 'bcrypt'
tokens:
  - $2y$12$bGtYgiRZXrCesMbcg4GHhOyTcyWmKTAzKzqgrVmjM3a/AGSSWUYHG # supportme
